### ISSUE TITLE
Not properly centered in 1440p 

### ISSUE THREAD

**Issue by brian6932** [DarkThemeHub/GoogleCentered#1]
While in 1440p the search box and results appear on the left rather properly in the center.
![image](https://user-images.githubusercontent.com/18603393/82152254-f33c7f80-982d-11ea-98c0-7954ba53dbe3.png)

**Comment by Snazzie** [comment]
Thanks for trying out this theme!

Yes, this is the current expected behavior. 

> results appear on the left rather properly in the center

Stylus (the theme injector) only has the capability to inject CSS style, so it's not possible to do what you're suggesting as that would require some javascript conditions to determine if there are any content on the right. (Which can be solved if i deploy a dedicated browser extension)

That being said, the intention of this theme is to position the google search page to the middle of the screen without changing the default google experience.

**Comment by brian6932** [comment]
you may say that but there are legitimate userstyles that do this, like this one for example: https://userstyles.org/styles/149976/center-google-search-results-improved

**Comment by Snazzie** [comment]
As my mention about not being able to detect right side content through css only.

This introduces the problem of asymmetrical layout seen below.

![image](https://user-images.githubusercontent.com/19627023/82154280-a922c080-9864-11ea-9f9f-9d2967ae23c6.png)

**Comment by Snazzie** [comment]
Hope that clears up the reason for wanting to keep the current behaviour :)
